### ISSUE TITLE
如何进行数据可视化

### ISSUE THREAD

**Issue by ZuoZicheng** [hzlllll/simple-vqa#1]
您好，感谢你提供了如此通俗易懂的项目，使我对于VQA有了一定的了解。
但是当我想要进行数据可视化操作，如注意力热图的时候遇到了一些问题。model文件中数据的格式为Keras Tensor，我想要转换为ndarray，但是由于tensorflow的版本不能用eval( )方法，使用numpy( )方法的时候会报错：AttributeError: 'KerasTensor' object has no attribute 'numpy'
请问有什么解决的办法吗？

**Comment by hzlllll** [comment]
可以尝试用torch改写一下模型，模型结构整体比较简单的
